apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: omjaju18/weather-app:v20260103150330
        ports:
        - containerPort: 5000
